[package]
name = "lucerna-x11"
description = "Lucerna X11 / Cinnamon wallpaper backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
lucerna-core.workspace = true
